### ISSUE TITLE
Add a "Resources" page to the DOE Code 

### ISSUE THREAD

**Issue by jayjaybillings** [doecode/doecode.github.io#11]
Can we add a "Resources" page to the DOE Code website? This would be a simple page that lists talks, posters and other things that members of the team are presenting. @vowelllDOE and I will provide links and content.

**Comment by vowelllDOE** [comment]
I believe @andrewsmith4814 should cover this for us

**Comment by jayjaybillings** [comment]
Here are a couple of things to link to:
1) https://figshare.com/articles/billings_doecode_siamcse2017_20170301_jpg/4730203
2) [The attached PDF](https://github.com/doecode/doecode.github.io/files/831641/billings_doeHQ_20170221.pdf)
