### ISSUE TITLE
Use logo instead of text on page

### ISSUE THREAD

**Issue by stooksburysl** [doecode/doecode.github.io#2]
For doecode.github.io, we should use the logo instead of the text on the page. @jayjaybillings will upload the logo and post its location to this ticket.

**Comment by IanLee1521** [comment]
Are you looking for one of these? https://powerpedia.energy.gov/wiki/DOE_Seal_and_Logo

**Comment by jayjaybillings** [comment]
Actually, we have a new logo specifically for DOECode because we are not allowed to use the DOE Seal and Logo.

I need to upload the new logo and then I'll ask @darelf to update the page.
