### ISSUE TITLE
Add website link

### ISSUE THREAD

**Issue by IanLee1521** [doecode/doecode.github.io#5]
It would be helpful to update the Website URL for this repo (and probably also https://github.com/doecode/doecode) to point to --  https://doecode.github.io

This can be done via the same "Edit" menu at the top of the repo where you enter the repo description:

<img width="1009" alt="screen shot 2016-10-22 at 10 08 20" src="https://cloud.githubusercontent.com/assets/828452/19621106/974ab684-983f-11e6-8c2f-45ad7a5e801b.png">

**Comment by jayjaybillings** [comment]
Done! Good catch!
